"""
Master configuration for Kast Cabinet Network.

Contains:
- SOURCES: Data source registry
- LEGAL_BASIS: Chilean transparency laws
- VERIFY_GUIDE: Step-by-step verification instructions
- CABINET: Full seed data for all 24 ministers
"""

SOURCES = {
    "infoprobidad": {"name": "InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado", "icon": "📋", "desc": "Declaraciones de patrimonio e intereses", "type": "portal"},
    "chilecompra": {"name": "Mercado Público", "url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx", "icon": "🛒", "desc": "Portal de compras públicas del Estado", "type": "portal"},
    "infolobby": {"name": "InfoLobby", "url": "https://www.leylobby.gob.cl/", "icon": "🤝", "desc": "Registro de audiencias, viajes y donativos", "type": "portal"},
    "sii": {"name": "SII Empresas", "url": "https://www.sii.cl/sobre_el_sii/nominapersonasjuridicas.html", "icon": "🏢", "desc": "Nómina de personas jurídicas y empresas", "type": "portal"},
    "opendata_cc": {"name": "Datos Abiertos ChileCompra", "url": "https://datos-abiertos.chilecompra.cl", "icon": "📊", "desc": "Bulk OCDS data downloads (CC0 license)", "type": "opendata"},
    "opendata_ip": {"name": "Datos Abiertos InfoProbidad", "url": "https://www.infoprobidad.cl/DatosAbiertos/DatosAbiertos", "icon": "📊", "desc": "Declaraciones en formato abierto + SPARQL", "type": "opendata"},
    "opendata_il": {"name": "API InfoLobby", "url": "https://www.leylobby.gob.cl/api/v1/", "icon": "📊", "desc": "API REST pública de audiencias (no auth needed)", "type": "opendata"},
    "bcn": {"name": "Biblioteca del Congreso", "url": "https://opendata.camara.cl", "icon": "🏛", "desc": "Datos abiertos parlamentarios", "type": "opendata"},
    "transparencia": {"name": "Portal Transparencia", "url": "https://www.portaltransparencia.cl/PortalPdT/", "icon": "🔎", "desc": "Transparencia activa del Estado", "type": "opendata"},
    "tdlc": {"name": "TDLC", "url": "https://www.tdlc.cl/", "icon": "⚖️", "desc": "Tribunal de Defensa de la Libre Competencia", "type": "reference"},
    "geneanexus": {"name": "Geneanexus", "url": "https://www.genealog.cl/", "icon": "🔍", "desc": "Búsqueda RUT empresas y personas", "type": "reference"},
    "ciper": {"name": "CIPER Chile", "url": "https://www.ciperchile.cl/2026/02/10/los-15-registros-que-describen-el-rol-del-futuro-ministro-de-hacienda-jorge-quiroz-a-favor-de-empresas-sancionadas-por-colusion/", "icon": "📰", "desc": "Investigación: 15 registros de Quiroz en colusión", "type": "journalism"},
    "latercera": {"name": "La Tercera", "url": "https://www.latercera.com/pulso/noticia/jorge-quiroz-alista-su-desembarco-en-hacienda-y-se-separa-de-los-socios-de-su-consultora/", "icon": "📰", "desc": "Red corporativa y separación de socios Quiroz", "type": "journalism"},
    "contrapoder": {"name": "Contrapoder Chile", "url": "https://contrapoderchile.cl/las-millonarias-asesorias-entre-la-empresa-del-coordinador-economico-de-kast-jorge-quiroz-y-el-gobierno-de-sebastian-pinera/", "icon": "📰", "desc": "Contratos Quiroz con gobierno Piñera", "type": "journalism"},
    "conadecus": {"name": "Conadecus", "url": "https://www.conadecus.cl/jorge-quiroz-el-economista-pro-colusion-y-anti-consumidores/", "icon": "📰", "desc": "Análisis rol Quiroz en casos colusión", "type": "journalism"},
    "wikipedia_quiroz": {"name": "Wikipedia - Jorge Quiroz", "url": "https://es.wikipedia.org/wiki/Jorge_Quiroz", "icon": "📖", "desc": "Biografía y trayectoria", "type": "reference"},
}

LEGAL_BASIS = [
    {"law": "Ley 20.285 (2008)", "desc": "Transparencia: obliga a publicar datos de gobierno", "url": "https://www.bcn.cl/leychile/navegar?idNorma=276363"},
    {"law": "Ley 20.730 (2014)", "desc": "Lobby: obliga a registrar audiencias con autoridades", "url": "https://www.bcn.cl/leychile/navegar?idNorma=1060115"},
    {"law": "Ley 20.880 (2016)", "desc": "Probidad: obliga a declarar patrimonio e intereses", "url": "https://www.bcn.cl/leychile/navegar?idNorma=1086062"},
]

VERIFY_GUIDE = {
    "patrimonio": {"label": "Declaraciones de patrimonio", "steps": "Ve a infoprobidad.cl → busca por nombre del ministro → revisa participaciones en empresas, bienes raíces, vehículos.", "url": "https://www.infoprobidad.cl/Home/Listado"},
    "contratos": {"label": "Contratos públicos", "steps": "Ve a mercadopublico.cl → Búsqueda Avanzada → ingresa RUT de empresa (ej: 96.953.120-8) en campo proveedor → revisa órdenes de compra.", "url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
    "lobby": {"label": "Reuniones de lobby", "steps": "Ve a leylobby.gob.cl → busca institución (ej: Ministerio de Hacienda) → selecciona sujeto pasivo → revisa audiencias, viajes, donativos.", "url": "https://www.leylobby.gob.cl/"},
    "empresas": {"label": "Empresas (RUT)", "steps": "Ve a sii.cl → descarga nómina de personas jurídicas → busca por RUT para ver actividad económica, tamaño, dirección.", "url": "https://www.sii.cl/sobre_el_sii/nominapersonasjuridicas.html"},
}

CABINET = [
    {
        "id": "jorge-quiroz",
        "name": "Jorge Antonio Quiroz Castro",
        "role": "Ministro de Hacienda",
        "ministry": "Ministerio de Hacienda",
        "ministry_transparency_url": "https://www.hacienda.cl/transparencia",
        "party": "Independiente",
        "rut": "",
        "status": "mapped",
        "sources": ["wikipedia_quiroz", "ciper", "latercera", "contrapoder", "conadecus"],
        "verify_urls": [
            {"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"},
            {"label": "Perfil Wikipedia", "url": "https://es.wikipedia.org/wiki/Jorge_Quiroz"},
        ],
        "known_companies": [
            {
                "name": "Jorge Quiroz C. y Consultores Asociados SA (now QA Consultores)",
                "rut": "96.953.120-8",
                "relationship": "Founder/controller (exited Jan 2026)",
                "sources": ["latercera", "geneanexus"],
                "verify_urls": [
                    {"label": "Ver RUT en Geneanexus", "url": "https://www.genealog.cl/Geneanexus/empresa/CHILE/TOTY5TwNTMxMjAtOA-jTw/nombre-y-rut/QUIROZ-Y-ASOCIADOS-S.A.-96953120-8"},
                    {"label": "Buscar en Mercado Público", "url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
                ],
            },
            {
                "name": "QYA Consultores Ltda. (ex Quiroz y Asociados Consultores Ltda.)",
                "rut": "",
                "relationship": "57.97% owner (exited Jan 2026)",
                "sources": ["latercera"],
                "verify_urls": [
                    {"label": "Buscar en SII", "url": "https://www.sii.cl/sobre_el_sii/nominapersonasjuridicas.html"},
                ],
            },
        ],
        "known_associates": [
            {"name": "Mónica Ríos", "relationship": "Cónyuge. Asesora Min. Economía (Piñera I, 2010-14), Jefa asesores MOP (Piñera II)", "sources": ["latercera"], "flags": ["REVOLVING_DOOR"]},
            {"name": "Felipe Givovich Díaz", "relationship": "Socio QA 58.81% (desde 2003)", "sources": ["latercera"]},
            {"name": "Jorge Bravo Tamayo", "relationship": "Socio QA 41.19%, ex-Banco Central", "sources": ["latercera"]},
            {"name": "Paula Hurtado Edwards", "relationship": "Ex-socia QA (salió ene 2026 con Quiroz)", "sources": ["latercera"]},
            {"name": "Tomás Bunster", "relationship": "Asociado QA 3+ años, vocero económico campaña Kast, posible dir. DIPRES", "sources": ["latercera"]},
        ],
        "known_gov_contracts": [
            {"buyer": "Subsecretaría de Economía", "year": 2011, "amount_clp": 28953823, "desc": "Asesoría gestión estratégica + análisis cabotaje", "sources": ["contrapoder"], "verify_url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
            {"buyer": "Subsecretaría Min. Vivienda y Urbanismo", "year": 2012, "amount_clp": 23000000, "desc": "Estudio factibilidad seguro construcción", "sources": ["contrapoder"], "verify_url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
            {"buyer": "Ministerio Segpres", "year": 2013, "amount_clp": 10000000, "desc": "Evaluación política cabotaje aéreo", "sources": ["contrapoder"], "verify_url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
            {"buyer": "Ministerio Segpres", "year": 2013, "amount_clp": 10000000, "desc": "Evaluación portabilidad numérica", "sources": ["contrapoder"], "verify_url": "https://www.mercadopublico.cl/Portal/Modules/Site/Busquedas/BuscadorAvanzado.aspx"},
            {"buyer": "ENAP", "year": 2022, "amount_clp": None, "desc": "Asesor externo (vigente)", "sources": ["contrapoder"], "verify_url": "https://www.enap.cl/transparencia/"},
        ],
        "collusion_links": [
            {"company": "Agrosuper / Ariztía / Don Pollo (vía APA)", "case": "Colusión avícola (1994-2010)", "role": "Creó modelo de proyección de ventas usado para repartir mercado", "sources": ["ciper", "tdlc"]},
            {"company": "Salcobrand", "case": "Colusión farmacias", "role": "Perito testigo, descartó colusión tras revisar 45K emails; tribunal encontró prueba directa", "sources": ["ciper", "tdlc"]},
            {"company": "Asfaltos Chilenos", "case": "Colusión asfalto", "role": "Análisis de mercado post-acusación", "sources": ["ciper"]},
            {"company": "MOL (Mitsui O.S.K. Lines)", "case": "Colusión navieras (car carriers)", "role": "Argumentó multa excesiva; TDLC inicial $2.5M, Corte Suprema elevó a $30.5M total", "sources": ["ciper"]},
            {"company": "Metrogas", "case": "Arbitraje regulatorio", "role": "Asesoría en split corporativo que elevó precios gas 12.7-20.2%", "sources": ["conadecus"]},
        ],
        "board_memberships": [
            {"entity": "Bolsa de Comercio de Santiago", "status": "Renunció ene 2026 tras nominación", "sources": ["wikipedia_quiroz"]},
        ],
        "corporate_events": [
            {"date": "2025-08", "event": "Ambas sociedades renombradas durante campaña: Quiroz y Asociados → QYA, Jorge Quiroz C. → QA", "sources": ["latercera"]},
            {"date": "2026-01", "event": "Quiroz + Hurtado salen de QYA. Givovich (58.81%) + Bravo (41.19%) quedan.", "sources": ["latercera"]},
        ],
        "notes": "Economista PUC/U.Chile. Coordinador económico campaña Kast. Fundador QA Consultores. Perito en casos de colusión: avícola, farmacias, asfalto, navieras.",
    },
    {
        "id": "claudio-alvarado",
        "name": "Claudio Alvarado Andrade",
        "role": "Ministro del Interior y Seguridad Pública",
        "ministry": "Ministerio del Interior",
        "ministry_transparency_url": "https://www.interior.gob.cl/transparencia/",
        "party": "UDI",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [
            {"label": "Buscar en BCN", "url": "https://www.bcn.cl/historiapolitica/resenas_parlamentarias/index.html"},
            {"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"},
        ],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Ex-diputado UDI. Ministro Segpres en ambos gobiernos Piñera. Encargado del traspaso de mando Boric→Kast.",
    },
    {
        "id": "francisco-perez-mackenna",
        "name": "Francisco Pérez Mackenna",
        "role": "Ministro de Relaciones Exteriores",
        "ministry": "Ministerio de RR.EE.",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "fernando-barros-tocornal",
        "name": "Fernando Barros Tocornal",
        "role": "Ministro de Defensa Nacional",
        "ministry": "Ministerio de Defensa",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Abogado. Integró el equipo defensor de Pinochet (Caso Riggs).",
    },
    {
        "id": "trinidad-steinert",
        "name": "Trinidad Steinert Herrera",
        "role": "Ministra de Seguridad Pública",
        "ministry": "Ministerio de Seguridad Pública",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Fiscal de la región de Tarapacá. Zona fronteriza clave para inmigración.",
    },
    {
        "id": "jose-garcia-ruminot",
        "name": "José García Ruminot",
        "role": "Ministro Secretario General de la Presidencia",
        "ministry": "Ministerio Segpres",
        "ministry_transparency_url": "https://www.segpres.gob.cl/transparencia/",
        "party": "Renovación Nacional",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [
            {"label": "Ficha BCN", "url": "https://www.bcn.cl/historiapolitica/resenas_parlamentarias/index.html"},
            {"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"},
        ],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Ex-senador Araucanía (2018-2026). Ex-presidente del Senado (2024-2025). Cargos en dictadura: alcalde de Toltén (1980), Lautaro (1984), Temuco (1986). RN desde 1989.",
    },
    {
        "id": "mara-sedini",
        "name": "Mara Sedini Viancos",
        "role": "Ministra Secretaria General de Gobierno",
        "ministry": "Ministerio Segob",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "daniel-mas-valdes",
        "name": "Daniel Mas Valdés",
        "role": "Ministro de Economía, Fomento y Turismo / Ministro de Minería",
        "ministries": [
            {"name": "Ministerio de Economía, Fomento y Turismo", "transparency_url": "https://www.economia.gob.cl/transparencia/"},
            {"name": "Ministerio de Minería", "transparency_url": "https://www.minmineria.gob.cl/transparencia/"},
        ],
        "ministry": "Ministerio de Economía / Ministerio de Minería",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Holds both Economía and Minería portfolios simultaneously.",
    },
    {
        "id": "maria-wulf",
        "name": "María Jesús Wulf Le May",
        "role": "Ministra de Desarrollo Social y Familia",
        "ministry": "Ministerio de Desarrollo Social",
        "party": "Partido Republicano",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Socióloga PUC. Fundadora red gremialista 'Movamos'. Ex-directora Fundación Jaime Guzmán. Subdirectora Acción Republicana.",
    },
    {
        "id": "maria-paz-arzola",
        "name": "María Paz Arzola González",
        "role": "Ministra de Educación",
        "ministry": "Ministerio de Educación",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "fernando-rabat",
        "name": "Fernando Rabat Celis",
        "role": "Ministro de Justicia y Derechos Humanos",
        "ministry": "Ministerio de Justicia",
        "ministry_transparency_url": "https://www.minjusticia.gob.cl/transparencia/",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [],
        "corporate_events": [
            {"date": "historical", "event": "Miembro del equipo defensor de Pinochet en Caso Riggs (cuentas bancarias secretas EEUU)", "sources": []},
        ],
        "notes": "Académico U. del Desarrollo. Socio fundador Barros & Errázuriz (1988). Decano Derecho U. Finis Terrae.",
    },
    {
        "id": "tomas-rau",
        "name": "Tomás Rau Binder",
        "role": "Ministro de Trabajo y Previsión Social",
        "ministry": "Ministerio del Trabajo",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "martin-arrau",
        "name": "Martín Arrau García-Huidobro",
        "role": "Ministro de Obras Públicas",
        "ministry": "Ministerio de Obras Públicas",
        "ministry_transparency_url": "https://www.mop.cl/transparencia/",
        "party": "Partido Republicano",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "may-chomali",
        "name": "May Chomalí Garib",
        "role": "Ministra de Salud",
        "ministry": "Ministerio de Salud",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "ivan-poduje",
        "name": "Iván Poduje Capdeville",
        "role": "Ministro de Vivienda y Urbanismo",
        "ministry": "Ministerio de Vivienda",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "jaime-campos",
        "name": "Jaime Campos Quiroga",
        "role": "Ministro de Agricultura",
        "ministry": "Ministerio de Agricultura",
        "party": "Partido Radical",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "louis-de-grange",
        "name": "Louis de Grange Concha",
        "role": "Ministro de Transportes y Telecomunicaciones",
        "ministry": "Ministerio de Transportes",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "catalina-parot",
        "name": "Catalina Parot Donoso",
        "role": "Ministra de Bienes Nacionales",
        "ministry": "Ministerio de Bienes Nacionales",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "ximena-rincon",
        "name": "Ximena Rincón González",
        "role": "Ministra de Energía",
        "ministry": "Ministerio de Energía",
        "party": "Demócratas",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [
            {"label": "Ficha BCN", "url": "https://www.bcn.cl/historiapolitica/resenas_parlamentarias/index.html"},
            {"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"},
        ],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Ex-senadora Maule (2018-2026). Ex-ministra Segpres y Trabajo bajo Bachelet II. Presidenta Demócratas. Ex-directora AFP Provida.",
    },
    {
        "id": "francisca-toledo",
        "name": "Francisca Ignacia Toledo Echegaray",
        "role": "Ministra de Medio Ambiente",
        "ministry": "Ministerio de Medio Ambiente",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "Ing. Civil Industrial PUC. Máster derecho regulatorio. Investigadora Libertad y Desarrollo. Asesora gabinete Presidencia Piñera II (2018-2020). Ex-gerenta Cámara Marítima.",
    },
    {
        "id": "natalia-duco",
        "name": "Natalia Duco Soler",
        "role": "Ministra de Deporte",
        "ministry": "Ministerio del Deporte",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "judith-marin",
        "name": "Judith Marín Morales",
        "role": "Ministra de la Mujer y la Equidad de Género",
        "ministry": "Ministerio de la Mujer",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "francisco-undurraga",
        "name": "Francisco Undurraga Gazitúa",
        "role": "Ministro de las Culturas, las Artes y el Patrimonio",
        "ministry": "Ministerio de las Culturas",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
    {
        "id": "ximena-lincolao",
        "name": "Ximena Lincolao Gates",
        "role": "Ministra de Ciencia, Tecnología, Conocimiento e Innovación",
        "ministry": "Ministerio de Ciencia",
        "party": "Independiente",
        "rut": "",
        "status": "seed",
        "sources": [],
        "verify_urls": [{"label": "Buscar en InfoProbidad", "url": "https://www.infoprobidad.cl/Home/Listado"}],
        "known_companies": [], "known_associates": [], "known_gov_contracts": [],
        "collusion_links": [], "board_memberships": [], "corporate_events": [],
        "notes": "",
    },
]
